version: "3"
services:
  frontend:
    image: frontend
    volumes:
      - ./frontend:/frontend
    network_mode: host
    command: quasar dev
  backend:
    image: backend
    volumes:
      - ./backend:/backend
    network_mode: host
    command: air
